version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: demether-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - demether-network

volumes:
  mongodb_data:
    driver: local

networks:
  demether-network:
    driver: bridge 